apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment1
  labels:
    app: deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
        - name: {{ .Release.Name}}
          image: docker.io/wollfieh/ng:latest
          ports:
            - containerPort: 3333
          env:
            - name: FOO
              value: "deployment1"
