apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment2
  labels:
    app: deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
        - name: {{ .Release.Name}}
          image: docker.io/wollfieh/ng:latest
          ports:
            - containerPort: 3333
          env:
            - name: FOO
              value: "deployment2"
