apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /service1
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc1
            port:
              name: http
      - path: /service2
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc2
            port:
              name: http
